env = Environment(
	MSVC_VERSION='12.0',
	TARGET_ARCH='x86')
debug = ARGUMENTS.get('debug', 0)
if int(debug):
   env.Append(CCFLAGS = ['/MDd', '/Od', '/DDEBUG', '/D_DEBUG'])
   env.Append(LINKFLAGS = ['/DEBUG'])
env.Program('hello.c')